### ISSUE TITLE
correct way to call readValue method

### ISSUE THREAD

**Issue by hermanghub** [mk-5/gdx-fireapp#4]
My first attempt to call readValue is as suggested in the read.me as readValue(List.class, new DataCallback<List<MyClass>>(). However, when I tried to retrieve MyClass record from the List I got something like "cannot cast HashMap to MyClass" run time exception error when running.

Finally, I made a workaround to call as readValue(Map.class, new DataCallback<Map<String, Object>>()) and then manually parsing the received HashMap object and convert it into a List of MyClass records.

Please find my MyClass as below:
public class MyClass {
    public String initials;
    public String dateTime;
    public String remarks;

    public MyClass() {}
    public MyClass(String initials, String dateTime, String remarks) {
        this.initials = initials;
        this.dateTime = dateTime;
        this.remarks = remarks;
    }

    public String getInitials() {
        return initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}

What should I change so that I do not need to manually convert the HashMap object to List<MyClass>? Thanks in advance.

Herman

**Comment by mk-5** [comment]
Hi!

Can you put some sample code how do you call the GdxFireapp API?

**Comment by hermangh** [comment]
I resolved this by calling like this:
... readValue(List.class, new DataCallback<List<Map<String, Object>>() {
                       @Override
                        public void onData(List<Map<String, Object> data)
                        {
                              (do the manual casting from Map to MyClass here)  
                        }

                        @Override
                        public void onError(Exception e)
                        {}
});

**Comment by mk-5** [comment]
So, ok - if you call like this `readValue(List.class, new DataCallback<List<MyClass>>` you received ClassCastException.

If DataCallback looks as follow: `DataCallback<R>` and R is a list, api retrieving generic type from List and should make deserialization for you before return data. 

What platform did you use? It can help me to find the issue because deserialization from DB has different implementation on each platform. 
Android platfrom API using default Firebase SDK deserialization. So returned type reflects your DB structure. Following types are allowed for many rows on Firebase Android SDK:
`Map<String, Object>` and `List<Object>` - [api docs here](https://firebase.google.com/docs/database/android/read-and-write#basic_write).

Android DataSnapshot reflects the type from your database.  So the problem is firebase API returned Map<String,Object> and GdxFireapp try to cast it to return type given inside DataCallback generic.


It's a chance that data/rows structure inside your DB which you try to read are not a List?

**Comment by hermangh** [comment]
I'm running on a iPad mini 2.

I've uploaded the JSON export of my database here -> https://github.com/hermangh/posting/blob/master/ht-bingo-c1d01-export.json

Please see if that explain why the simple structure cannot be deserialised properly. Thanks.

**Comment by mk-5** [comment]
Thanks, this will be very helpful. 
I'll check it soon - this week - and then get some fix

**Comment by mk-5** [comment]
Please check version 1.2.0. 

````java
GdxFIRDatabase.instance().inReference("/my-list")
                  .readValue(List.class, new DataCallback<List<MyClass>>()
                    {
                        @MapConversion(MyClass.class)
                        @Override
                        public void onData(List<MyClass> data)
                        {  }

                        @Override
                        public void onError(Exception e)
                        {}
                    });
````

**Comment by hermanghub** [comment]
Thanks. I'll try v1.2.0

Will let you know the result. Thanks.

**Comment by hermangh** [comment]
Sorry for the long wait. I'm using v1.3.1 and the read value method works perfectly into the List<MyClass> variable. Thank you so much!

**Comment by hermanghub** [comment]
Sorry got multiple accounts. Problem solved! Thanks.
